In [3]:
import pandas as pd
import numpy as np
letters=pd.read_csv("letterdata.csv")
letters.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [5]:
"""Data set typically contains handwritten chareacters
letter :represents the target class
Features: this are numeric attributes describing various geometric or statastical properties of the chgaracters
xbox and ybox: x and y bounding box dimensions
width and height : width and height of the character bounding box
onpix:number of on-pixels in characters image
xbar and ybar : Mean X and Y coordib=nate valuesof on-pixels
x2bar,y2bar,and xybar : variance and covarience of pixel intensities
x2ybar and xy2bar : additional"""

'Data set typically contains handwritten chareacters\nletter :represents the target class\nFeatures: this are numeric attributes describing various geometric or statastical properties of the chgaracters\nxbox and ybox: x and y bounding box dimensions\nwidth and height : width and height of the character bounding box\nonpix:number of on-pixels in characters image\nxbar and ybar : Mean X and Y coordib=nate valuesof on-pixels\nx2bar,y2bar,and xybar : variance and covarience of pixel intensities\nx2ybar and xy2bar : additional'

In [13]:
#let us carry out EDA
letters.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [23]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
train,test=train_test_split(letters,test_size=0.2)

In [33]:
#Let us split the data in terms of X and Y for both train and test data
train_X=train.iloc[:,1:]
train_y=train.iloc[:,0]
test_X=test.iloc[:,1:]
test_y=test.iloc[:,0]

In [35]:
#Kernel linear 
model_linear=SVC(kernel="linear")
model_linear.fit(train_X,train_y)
pred_test_linear=model_linear.predict(test_X)

In [37]:
#now let us check the acuracy
np.mean(pred_test_linear==test_y)

0.856

In [39]:
#Kernel rbf
#Kernel linear 
model_rbf=SVC(kernel="rbf")
model_rbf.fit(train_X,train_y)
pred_test_rbf=model_rbf.predict(test_X)

In [41]:
#now let us check the acuracy
np.mean(pred_test_rbf==test_y)

0.92875